name: Copilot Setup

on:
  copilot-api:

jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-25.05

      - name: Install flake packages
        run: |
          nix develop --impure -c echo "Nix environment set up successfully"

      - name: Test environment setup
        run: |
          nix develop --impure -c just --list
