name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint || echo "Linting not configured"
    
    - name: Run tests
      run: npm test -- run
    
    - name: Build Storybook
      run: npm run build-storybook
    
    - name: Build application
      run: npm run build
    
    - name: Run Storybook tests
      run: npm run test-storybook
    
    - name: Upload Storybook build
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: storybook-static
        path: frontend/storybook-static/
        retention-days: 7
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: coverage-report
        path: frontend/coverage/
        retention-days: 7

  storybook-visual-tests:
    runs-on: ubuntu-latest
    needs: test-frontend
    if: github.event_name == 'pull_request'
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Download Storybook build
      uses: actions/download-artifact@v4
      with:
        name: storybook-static
        path: frontend/storybook-static/
    
    - name: Run visual regression tests (placeholder)
      run: |
        echo "🎨 Visual regression tests would run here"
        echo "Consider integrating with Chromatic, Percy, or similar tools"
        echo "Storybook build is available at: $(pwd)/storybook-static/"
        ls -la storybook-static/