name: Frontend CI

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.node-version' # Uses the version from .node-version
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx,.js,.jsx
        working-directory: ./frontend

      - name: Run Vitest unit tests with coverage
        run: npm run test:coverage
        working-directory: ./frontend

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: frontend/coverage/ # Default Vitest coverage directory

      - name: Run Pact contract tests
        run: npm run test:pact
        working-directory: ./frontend
