name: Frontend CI

on:
  push:
    branches: [main, staging, trying]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx eslint .

      - name: Run tests
        run: npm test -- --run

      - name: Build frontend
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: frontend/storybook-static
          retention-days: 7

  # Optional: Add Storybook test-runner job once configured
  # storybook-tests:
  #   runs-on: ubuntu-latest
  #   needs: test
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "npm"
  #         cache-dependency-path: frontend/package-lock.json
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Install Playwright
  #       run: npx playwright install --with-deps
  #
  #     - name: Build Storybook
  #       run: npm run build-storybook
  #
  #     - name: Run Storybook tests
  #       run: npx test-storybook
