name: Build & publish devcontainer image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    name: Build and publish devcontainer image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push devcontainer image
        uses: docker/build-push-action@v4
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/caLANdar-devcontainer:latest
            ghcr.io/${{ github.repository_owner }}/caLANdar-devcontainer:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
