name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@e1c2ff9b0d68adb0b2cfb35e29edfb335b854e41 # v2 latest commit
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JKZY7KYNJ0KZZDKGDW9W1KAF
          working-directory: api
          secrets: |
            PASETO_SECRET_KEY = '${{ secrets.PASETO_SECRET_KEY }}'
            RESEND_API_KEY = '${{ secrets.RESEND_API_KEY }}'
            STEAM_API_KEY = '${{ secrets.STEAM_API_KEY }}'
