name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          project-id: proj_01H1T42300G97DJDRF8PAYQVYF
          working-directory: api
